name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Yandex Container Registry
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.yandex
          push: true
          tags: cr.yandex/crplgktfkcdsrtriaqie/veilora-web:latest

      - name: Deploy to Serverless Container
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_KEY }}
          container-name: veilora-web
          folder-id: b1gnlfdgvsdpmp60a4d9
          revision-image-url: cr.yandex/crplgktfkcdsrtriaqie/veilora-web:latest
          revision-execution-timeout: 15s
          revision-cores: 1
          revision-memory: 4096MB
          revision-concurrency: 1
          revision-core-fraction: 100
